- name: "Update subscription auth server"
  replace:
      path: /etc/rhsm/rhsm.conf
      regexp: 'hostname = (.*)'
      replace: 'hostname = {{ auth_server }}'
      backup: yes

- name: Register as user ("{{ subscription_username }}").
  redhat_subscription:
      state: present
      username: "{{ subscription_username }}"
      password: "{{ subscription_password }}"
      autosubscribe: true

- name: Disable all repositories
  shell: subscription-manager repos --disable="*"

- name: Enable repositories
  shell: subscription-manager repos \
          --enable="rhel-7-server-rpms" \
          --enable="rhel-7-server-extras-rpms" \
          --enable="rhel-7-server-ose-{{ ocp_version }}-rpms" \
          --enable="rhel-7-fast-datapath-rpms" \
          --enable="rhel-7-server-ansible-2.4-rpms"

- name: Enable ansible rpms
  when: ocp_version == "3.9"
  shell: subscription-manager repos --enable="rhel-7-server-ansible-2.4-rpms"

- name: Installing delta RPM
  # Reason:
  #     https://unix.stackexchange.com/questions/277900/do-i-need-to-do-something-about-delta-rpms-disabled
  #     https://www.pks.mpg.de/~mueller/docs/suse10.2/html/opensuse-manual_en/manual/sec.rpm.delta.html
  yum:
      name: deltarpm
      state: latest
- name: Updating yum
  yum:
      name: '*'
      state: latest
- name: Installing reqired packages
  yum:
      name: "{{ item }}"
      state: latest
  with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - atomic-openshift-utils
      - docker

- name: Restarting dbus service
  shell: systemctl restart dbus

- name: Restarting nodes
  shell: nohup bash -c "sleep 2s && shutdown -r now" &

- name: Wait for nodes to come back
  wait_for_connection:
    timeout: 240
    delay: 20

- shell: sleep 10; systemctl status dbus
  register: dbus_status

- debug: 
  var: dbus_status
  verbosity: 2
